### ISSUE TITLE
Upgrade aws-sdk v1 => v3

### ISSUE THREAD

**Issue by sanak** [bizyman/redmine_s3#2]
I once gave up about this,
https://github.com/bizyman/redmine_s3/issues/1#issuecomment-519747138
but @aruneko mentioned that the following repository seems to support aws-sdk v2 already.
https://github.com/ganehag/redmine_s3

So, we will try to consider upgrading aws-sdk v1 => v3, later.

**Comment by eyewritecode** [comment]
I'm closing this since my last merge uses v3
